### PR TITLE
Content-Disposition filename gets garbled filename for Japanese Characters in Safari.

### PR DESCRIPTION
**Pull request by ggallotti**
This code :
`&HttpResponse.AddHeader(!"Content-Disposition", !'attachment;  filename=注文詳細.xlsx')`

Gets garbled http download filename in Safari. 

Change log:
- We now use RFC5987 " Character Set and Language Encoding for Hypertext Transfer Protocol (HTTP) Header Field Parameters" for encoding filename attribute inside Content-Disposition Header. We fallback to the original method when somethig fails.
- Safari does not support RFC5987 nor String encoded Filename atribute, so we disable encoding for this Browser until RFC5987 get supported.

### CODE REVIEW

**Review by claudiamurialdo — CHANGES_REQUESTED** [review]
Could GetEncodedContentDisposition be internal instead of public?

**Comment by ggallotti** [comment]
> Could GetEncodedContentDisposition be internal instead of public?

If I change to internal, UnitTest Project fails to compile. What do you suggest?

**Comment by claudiamurialdo** [comment]
> > Could GetEncodedContentDisposition be internal instead of public?
> 
> If I change to internal, UnitTest Project fails to compile. What do you suggest?

Try adding 
[assembly: InternalsVisibleTo("DotNetCoreUnitTest")]

to AssemblyInfo.cs of GxClasses.dll

**Comment by ggallotti** [comment]
@claudiamurialdo : This is ready to review. Thanks!

**Review by claudiamurialdo — APPROVED** [review]

**Pull request merged**
